---
- hosts: web
  become: yes
  gather_facts: no
  tasks:
  - name: Apache latest version installation
    dnf:
      name: httpd
      state: latest
  - name: Start httpd service
    service:
      name: httpd
      state: started
  - name: enable service httpd and ensure it is not masked
    systemd:
      name: httpd
      enabled: yes
      masked: no
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled

  handlers:
  - name: Restart apache service
    service:
      name: httpd
      state: restarted
